apiVersion: v1
kind: ConfigMap
metadata:
  name: chirpstack-application-server
  labels:
    app: chirpstack-application-server
data:
  chirpstack-application-server.toml: 
    {{ tpl (.Files.Get "files/config.toml") . | quote }}