apiVersion: v2
name: pihole
description: A Helm chart for pihole
type: application
version: 1.0.0
maintainers:
  - name: Johan Andersson
    email: contact@johanandersson.se
    url: www.johanandersson.se
keywords:
  - pihole
#dependencies:
#  - name: shared
#   version: 1.0.0
