apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
    {{- include "yggio.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
    {{- include "yggio.tplvalues.render" ( dict "value" .Values.service.annoations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
