apiVersion: v2
name: chirpstack-application-server
description: A Helm chart for the chirpstack application server
type: application
version: 0.1.0
appVersion: 3.14.0
home: https://www.chirpstack.io/
sources: 
  - https://hub.docker.com/r/chirpstack/chirpstack-application-server
deprecated: false
maintainers:
  - name: Johan Andersson
    email: contact@johanandersson.se
    url: www.johanandersson.se
keywords:
  - chirpstack
  - application
  - server
dependencies:
  - name: postgresql
    version: 10.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 14.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled